webapp/news/models.py
from datetime import datetime
from sqlalchemy.orm import relationship

from webapp.db import db


class News(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String, nullable=False)
    url = db.Column(db.String, unique=True, nullable=False)
    published = db.Column(db.DateTime, nullable=False)
    text = db.Column(db.Text, nullable=True)

    def comments_count(self):
        return Comments.query.filter(Comments.news_id == self.id).count()

    def __repr__(self):
        return '<News {} {}>'.format(self.title, self.url)


class Comments(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    text = db.Column(db.Text, nullable=True)
    created = db.Column(db.DateTime, nullable=False, default=datetime.now())
    news_id = db.Column(
        db.Integer,
        db.ForeignKey('news.id', ondelete='CASCADE'),
        index=True
    )
    user_id = db.Column(
        db.Integer,
        db.ForeignKey('user.id', ondelete='CASCADE'),
        index=True
    )

    news = relationship('News', backref='comments')
    user = relationship('User', backref='comments')

    def __repr__(self):
        return '<Comment {}>'.format(self.id)

webapp/news/forms.py
from flask_wtf import FlaskForm
from wtforms import HiddenField, StringField, SubmitField
from wtforms.validators import DataRequired, ValidationError

from webapp.news.models import News


class CommentForm(FlaskForm):
    news_id = HiddenField('News ID', validators=[DataRequired()])
    comment_text = StringField('Comment Text',
                               validators=[DataRequired()],
                               render_kw={"class": "form-control"})
    submit = SubmitField('Send comment!', render_kw={"class": "btn btn-primary"})

    def validate_news_id(self, news_id):
        if not News.query.get(news_id.data):
            raise ValidationError(
                    'You trying to comment news with nonexistent id')

webapp/news/views.py
from flask import abort, Blueprint, flash, current_app, render_template, redirect, request, url_for
from flask_login import current_user, login_required

from webapp.db import db
from webapp.news.forms import CommentForm
from webapp.news.models import Comments, News
from webapp.weather import weather_by_city
from webapp.utils import get_redirect_target

blueprint = Blueprint('news', __name__)


@blueprint.route('/')
def index():
    title = 'Python News'
    # weather = weather_by_city(app.config['WEATHER_DEFAULT_CITY'])
    weather = weather_by_city(current_app.config['WEATHER_DEFAULT_CITY'])
    news_list = News.query.filter(News.text.isnot(None)).order_by(News.published.desc()).all()
    return render_template('news/index.html', page_title=title,
                           weather=weather, news_list=news_list)


@blueprint.route('/news/<int:news_id>')
def single_news(news_id):
    my_news = News.query.filter(News.id == news_id).first()
    if not my_news:
        abort(404)

    form = CommentForm(news_id=my_news.id)
    return render_template(
        'news/single_news.html',
        page_title=my_news.title,
        news=my_news,
        comment_form=form
        )


@blueprint.route('/news/comment', methods=['POST'])
@login_required
def add_comment():
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comments(text=form.comment_text.data,
                           news_id=form.news_id.data,
                           user_id=current_user.id)
        db.session.add(comment)
        db.session.commit()
        flash('Comment successfully added')
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash('Error in field "{}": - {}'.format(
                    getattr(form, field).label.text,
                    error
                ))
    return redirect(get_redirect_target)

webapp/templates/news/index.html
{% extends "base.html" %}

{% block content %}
        <div class="row">
            <div class="col-8">
                {% include('messages.html') %}
                <h1>News</h1>
                {% for news in news_list %}
                <h3><a href='{{ url_for('news.single_news', news_id=news.id) }}'>{{news.title}}</a></h3>
                <p>{{ news.published.strftime("%d.%m.%Y в %H:%M") }} | Comments: {{ news.comments_count() }}</p>
                <hr />
                {% endfor %}
            </div>
            <div class="col-4">
                <h1>Weather</h1>
                <h3>
                {% if weather %}
                    Temperature is {{ weather.temp_C }}, feels like {{ weather.FeelsLikeC }}
                {% else %}
                    Service is unavailable
                {% endif %}</h3>
            </div>
        </div>
{% endblock %}

webapp/templates/news/single_news.html
{% extends "base.html" %}

{% block content %}
        <div class="row">
            <div class="col-8 news-content">
                {% include('messages.html') %}
                {{ news.text|safe }}
                {% if news.comments %}
                    <h3>Комментарии:</h3>
                    {% for comment in news.comments %}
                    <div class="card">
                        <div class="card-body">
                            <p class="card-text">{{ comment.text }}</p>
                            <p class="card-text">
                                <small>Опубликовано: {{ comment.created.strftime('%d.%m.%Y в %H:%M') }} | 
                                    Автор: {{ comment.user.username }}</small>
                            </p>
                        </div>
                    </div>
                    {% endfor %}
                {% endif %}
                {% if current_user.is_authenticated %}
                    <form action="{{ url_for('news.add_comment') }}" method="POST">
                        {{ comment_form.hidden_tag() }}
                        <div class="form-group">
                            {{ comment_form.comment_text.label }}
                            {{ comment_form.comment_text() }}
                        </div>
                        {{ comment_form.submit() }}
                    </form>
                {% else %}
                    <p><a href="{{ url_for('user.login', next=request.full_path) }}">Authetificate</a>, for adding comment</p>
                {% endif %}
            </div>
            <div class="col-4">
                <h1>Another news</h1>
            </div>
        </div>
{% endblock %}